sonar.organization=7feeh7
sonar.projectKey=7feeh7_tech-challenge-oficina
sonar.projectName=tech-challenge-api
sonar.projectVersion=1.0

# Fontes e testes
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/generated/**,**/*.module.ts,**/*.entity.ts,**/*.dto.ts,**/main.ts,prisma/**

# Cobertura (lcov gerado pelo Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/main.ts,**/*.module.ts,**/*.entity.ts,**/*.dto.ts,**/generated/**,**/dto/**,**/entities/**

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
