apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app: oficina-api
spec:
  # NodePort interno: trafego publico entra somente pelo API Gateway + NLB in-VPC.
  type: NodePort
  selector:
    app: oficina-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
